module.exports.colorlog = require('./colorlog')
module.exports.loader = require('./loader')
module.exports.error = require('./error')
module.exports.done = require('./done')
module.exports.blank = require('./blank')
module.exports.exit = require('./exit')
module.exports.finish = require('./finish')
module.exports.versionlog = require('./versionlog')
