<?php
/**
 * This is a config file generated by Deux.
 * Deux is a CLI tool for scaffolding WordPress theme.
 *
 * @link https://github.com/Ribhnux/deux-cli
 * @package {{theme.name}}
 * @since {{theme.version}}
 */

${{theme.slugfn}}_config = {{{config}}}
