<?php
/**
 * This is a config file generated by Deux.  
 * Deux is a CLI tool for scaffolding WordPress theme.
 *
 * @link https://github.com/Ribhnux/deux
 * @package {{themeName}}
 * @since {{version}}
 */

$theme_config = {{{themeConfig}}}
